// Mocks generated by Mockito 5.4.4 from annotations
// in venturelink/test/data/repositories/subscription_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_preferences/src/shared_preferences_legacy.dart' as _i7;
import 'package:venturelink/data/models/payment_session_model.dart' as _i4;
import 'package:venturelink/data/models/subscription_plan_model.dart' as _i3;
import 'package:venturelink/data/services/payment_api_service.dart' as _i5;
import 'package:venturelink/data/services/subscription_api_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePlanResponse_0 extends _i1.SmartFake implements _i2.PlanResponse {
  _FakePlanResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSubscriptionPlanModel_1 extends _i1.SmartFake
    implements _i3.SubscriptionPlanModel {
  _FakeSubscriptionPlanModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSubscriptionModel_2 extends _i1.SmartFake
    implements _i3.SubscriptionModel {
  _FakeSubscriptionModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCancelSubscriptionResponse_3 extends _i1.SmartFake
    implements _i2.CancelSubscriptionResponse {
  _FakeCancelSubscriptionResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaginatedResponse_4<T> extends _i1.SmartFake
    implements _i2.PaginatedResponse<T> {
  _FakePaginatedResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaymentSessionModel_5 extends _i1.SmartFake
    implements _i4.PaymentSessionModel {
  _FakePaymentSessionModel_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePromoCodeValidationResponse_6 extends _i1.SmartFake
    implements _i2.PromoCodeValidationResponse {
  _FakePromoCodeValidationResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaymentMethodsResponse_7 extends _i1.SmartFake
    implements _i5.PaymentMethodsResponse {
  _FakePaymentMethodsResponse_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaginatedResponse_8<T> extends _i1.SmartFake
    implements _i5.PaginatedResponse<T> {
  _FakePaginatedResponse_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAccountBalanceResponse_9 extends _i1.SmartFake
    implements _i5.AccountBalanceResponse {
  _FakeAccountBalanceResponse_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRefundResponse_10 extends _i1.SmartFake
    implements _i5.RefundResponse {
  _FakeRefundResponse_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SubscriptionApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionApiService extends _i1.Mock
    implements _i2.SubscriptionApiService {
  MockSubscriptionApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.PlanResponse> getSubscriptionPlans() => (super.noSuchMethod(
        Invocation.method(
          #getSubscriptionPlans,
          [],
        ),
        returnValue: _i6.Future<_i2.PlanResponse>.value(_FakePlanResponse_0(
          this,
          Invocation.method(
            #getSubscriptionPlans,
            [],
          ),
        )),
      ) as _i6.Future<_i2.PlanResponse>);

  @override
  _i6.Future<_i3.SubscriptionPlanModel> getSubscriptionPlanDetails(
          String? planId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubscriptionPlanDetails,
          [planId],
        ),
        returnValue: _i6.Future<_i3.SubscriptionPlanModel>.value(
            _FakeSubscriptionPlanModel_1(
          this,
          Invocation.method(
            #getSubscriptionPlanDetails,
            [planId],
          ),
        )),
      ) as _i6.Future<_i3.SubscriptionPlanModel>);

  @override
  _i6.Future<_i3.SubscriptionModel> createSubscription(
          _i2.CreateSubscriptionRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSubscription,
          [request],
        ),
        returnValue:
            _i6.Future<_i3.SubscriptionModel>.value(_FakeSubscriptionModel_2(
          this,
          Invocation.method(
            #createSubscription,
            [request],
          ),
        )),
      ) as _i6.Future<_i3.SubscriptionModel>);

  @override
  _i6.Future<_i3.SubscriptionModel> getCurrentSubscription() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentSubscription,
          [],
        ),
        returnValue:
            _i6.Future<_i3.SubscriptionModel>.value(_FakeSubscriptionModel_2(
          this,
          Invocation.method(
            #getCurrentSubscription,
            [],
          ),
        )),
      ) as _i6.Future<_i3.SubscriptionModel>);

  @override
  _i6.Future<_i2.CancelSubscriptionResponse> cancelSubscription(
    String? subscriptionId,
    _i2.CancelSubscriptionRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelSubscription,
          [
            subscriptionId,
            request,
          ],
        ),
        returnValue: _i6.Future<_i2.CancelSubscriptionResponse>.value(
            _FakeCancelSubscriptionResponse_3(
          this,
          Invocation.method(
            #cancelSubscription,
            [
              subscriptionId,
              request,
            ],
          ),
        )),
      ) as _i6.Future<_i2.CancelSubscriptionResponse>);

  @override
  _i6.Future<_i3.SubscriptionModel> updateSubscription(
    String? subscriptionId,
    _i2.UpdateSubscriptionRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSubscription,
          [
            subscriptionId,
            request,
          ],
        ),
        returnValue:
            _i6.Future<_i3.SubscriptionModel>.value(_FakeSubscriptionModel_2(
          this,
          Invocation.method(
            #updateSubscription,
            [
              subscriptionId,
              request,
            ],
          ),
        )),
      ) as _i6.Future<_i3.SubscriptionModel>);

  @override
  _i6.Future<_i2.PaginatedResponse<_i3.SubscriptionModel>>
      getSubscriptionHistory() => (super.noSuchMethod(
            Invocation.method(
              #getSubscriptionHistory,
              [],
            ),
            returnValue:
                _i6.Future<_i2.PaginatedResponse<_i3.SubscriptionModel>>.value(
                    _FakePaginatedResponse_4<_i3.SubscriptionModel>(
              this,
              Invocation.method(
                #getSubscriptionHistory,
                [],
              ),
            )),
          ) as _i6.Future<_i2.PaginatedResponse<_i3.SubscriptionModel>>);

  @override
  _i6.Future<_i3.SubscriptionModel> reactivateSubscription(
          String? subscriptionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #reactivateSubscription,
          [subscriptionId],
        ),
        returnValue:
            _i6.Future<_i3.SubscriptionModel>.value(_FakeSubscriptionModel_2(
          this,
          Invocation.method(
            #reactivateSubscription,
            [subscriptionId],
          ),
        )),
      ) as _i6.Future<_i3.SubscriptionModel>);

  @override
  _i6.Future<_i3.SubscriptionModel> changePlan(
    String? subscriptionId,
    _i2.ChangePlanRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePlan,
          [
            subscriptionId,
            request,
          ],
        ),
        returnValue:
            _i6.Future<_i3.SubscriptionModel>.value(_FakeSubscriptionModel_2(
          this,
          Invocation.method(
            #changePlan,
            [
              subscriptionId,
              request,
            ],
          ),
        )),
      ) as _i6.Future<_i3.SubscriptionModel>);

  @override
  _i6.Future<_i2.PaginatedResponse<_i2.PaymentHistoryModel>>
      getPaymentHistory() => (super.noSuchMethod(
            Invocation.method(
              #getPaymentHistory,
              [],
            ),
            returnValue: _i6
                .Future<_i2.PaginatedResponse<_i2.PaymentHistoryModel>>.value(
                _FakePaginatedResponse_4<_i2.PaymentHistoryModel>(
              this,
              Invocation.method(
                #getPaymentHistory,
                [],
              ),
            )),
          ) as _i6.Future<_i2.PaginatedResponse<_i2.PaymentHistoryModel>>);

  @override
  _i6.Future<_i4.PaymentSessionModel> createPaymentSession(
          _i2.CreatePaymentSessionRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPaymentSession,
          [request],
        ),
        returnValue: _i6.Future<_i4.PaymentSessionModel>.value(
            _FakePaymentSessionModel_5(
          this,
          Invocation.method(
            #createPaymentSession,
            [request],
          ),
        )),
      ) as _i6.Future<_i4.PaymentSessionModel>);

  @override
  _i6.Future<_i4.PaymentSessionModel> checkPaymentStatus(String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkPaymentStatus,
          [sessionId],
        ),
        returnValue: _i6.Future<_i4.PaymentSessionModel>.value(
            _FakePaymentSessionModel_5(
          this,
          Invocation.method(
            #checkPaymentStatus,
            [sessionId],
          ),
        )),
      ) as _i6.Future<_i4.PaymentSessionModel>);

  @override
  _i6.Future<_i4.PaymentSessionModel> confirmPayment(
    String? sessionId,
    _i2.ConfirmPaymentRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmPayment,
          [
            sessionId,
            request,
          ],
        ),
        returnValue: _i6.Future<_i4.PaymentSessionModel>.value(
            _FakePaymentSessionModel_5(
          this,
          Invocation.method(
            #confirmPayment,
            [
              sessionId,
              request,
            ],
          ),
        )),
      ) as _i6.Future<_i4.PaymentSessionModel>);

  @override
  _i6.Future<List<_i2.PaymentMethodModel>> getPaymentMethods() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaymentMethods,
          [],
        ),
        returnValue: _i6.Future<List<_i2.PaymentMethodModel>>.value(
            <_i2.PaymentMethodModel>[]),
      ) as _i6.Future<List<_i2.PaymentMethodModel>>);

  @override
  _i6.Future<_i2.PromoCodeValidationResponse> validatePromoCode(
          _i2.ValidatePromoCodeRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #validatePromoCode,
          [request],
        ),
        returnValue: _i6.Future<_i2.PromoCodeValidationResponse>.value(
            _FakePromoCodeValidationResponse_6(
          this,
          Invocation.method(
            #validatePromoCode,
            [request],
          ),
        )),
      ) as _i6.Future<_i2.PromoCodeValidationResponse>);
}

/// A class which mocks [PaymentApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentApiService extends _i1.Mock implements _i5.PaymentApiService {
  MockPaymentApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i5.PaymentMethodsResponse> getPaymentMethods() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaymentMethods,
          [],
        ),
        returnValue: _i6.Future<_i5.PaymentMethodsResponse>.value(
            _FakePaymentMethodsResponse_7(
          this,
          Invocation.method(
            #getPaymentMethods,
            [],
          ),
        )),
      ) as _i6.Future<_i5.PaymentMethodsResponse>);

  @override
  _i6.Future<_i4.PaymentSessionModel> createSubscriptionPayment(
          _i5.CreateSubscriptionPaymentRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSubscriptionPayment,
          [request],
        ),
        returnValue: _i6.Future<_i4.PaymentSessionModel>.value(
            _FakePaymentSessionModel_5(
          this,
          Invocation.method(
            #createSubscriptionPayment,
            [request],
          ),
        )),
      ) as _i6.Future<_i4.PaymentSessionModel>);

  @override
  _i6.Future<_i4.PaymentSessionModel> initiateDirectPayment(
          _i5.DirectPaymentRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #initiateDirectPayment,
          [request],
        ),
        returnValue: _i6.Future<_i4.PaymentSessionModel>.value(
            _FakePaymentSessionModel_5(
          this,
          Invocation.method(
            #initiateDirectPayment,
            [request],
          ),
        )),
      ) as _i6.Future<_i4.PaymentSessionModel>);

  @override
  _i6.Future<_i4.PaymentSessionModel> authorizePaymentOTP(
          _i5.AuthorizeOTPRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #authorizePaymentOTP,
          [request],
        ),
        returnValue: _i6.Future<_i4.PaymentSessionModel>.value(
            _FakePaymentSessionModel_5(
          this,
          Invocation.method(
            #authorizePaymentOTP,
            [request],
          ),
        )),
      ) as _i6.Future<_i4.PaymentSessionModel>);

  @override
  _i6.Future<_i4.PaymentSessionModel> checkPaymentStatus(String? paymentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkPaymentStatus,
          [paymentId],
        ),
        returnValue: _i6.Future<_i4.PaymentSessionModel>.value(
            _FakePaymentSessionModel_5(
          this,
          Invocation.method(
            #checkPaymentStatus,
            [paymentId],
          ),
        )),
      ) as _i6.Future<_i4.PaymentSessionModel>);

  @override
  _i6.Future<_i5.PaginatedResponse<_i5.PaymentHistoryModel>>
      getPaymentHistory() => (super.noSuchMethod(
            Invocation.method(
              #getPaymentHistory,
              [],
            ),
            returnValue: _i6
                .Future<_i5.PaginatedResponse<_i5.PaymentHistoryModel>>.value(
                _FakePaginatedResponse_8<_i5.PaymentHistoryModel>(
              this,
              Invocation.method(
                #getPaymentHistory,
                [],
              ),
            )),
          ) as _i6.Future<_i5.PaginatedResponse<_i5.PaymentHistoryModel>>);

  @override
  _i6.Future<_i5.AccountBalanceResponse> getAccountBalance() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccountBalance,
          [],
        ),
        returnValue: _i6.Future<_i5.AccountBalanceResponse>.value(
            _FakeAccountBalanceResponse_9(
          this,
          Invocation.method(
            #getAccountBalance,
            [],
          ),
        )),
      ) as _i6.Future<_i5.AccountBalanceResponse>);

  @override
  _i6.Future<_i4.PaymentSessionModel> createPayment(
          _i5.CreatePaymentRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPayment,
          [request],
        ),
        returnValue: _i6.Future<_i4.PaymentSessionModel>.value(
            _FakePaymentSessionModel_5(
          this,
          Invocation.method(
            #createPayment,
            [request],
          ),
        )),
      ) as _i6.Future<_i4.PaymentSessionModel>);

  @override
  _i6.Future<_i5.RefundResponse> refundPayment(
    String? paymentId,
    _i5.RefundRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #refundPayment,
          [
            paymentId,
            request,
          ],
        ),
        returnValue:
            _i6.Future<_i5.RefundResponse>.value(_FakeRefundResponse_10(
          this,
          Invocation.method(
            #refundPayment,
            [
              paymentId,
              request,
            ],
          ),
        )),
      ) as _i6.Future<_i5.RefundResponse>);

  @override
  _i6.Future<_i4.PaymentSessionModel> updatePaymentStatus(String? paymentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePaymentStatus,
          [paymentId],
        ),
        returnValue: _i6.Future<_i4.PaymentSessionModel>.value(
            _FakePaymentSessionModel_5(
          this,
          Invocation.method(
            #updatePaymentStatus,
            [paymentId],
          ),
        )),
      ) as _i6.Future<_i4.PaymentSessionModel>);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i7.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() => (super.noSuchMethod(
        Invocation.method(
          #getKeys,
          [],
        ),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  Object? get(String? key) => (super.noSuchMethod(Invocation.method(
        #get,
        [key],
      )) as Object?);

  @override
  bool? getBool(String? key) => (super.noSuchMethod(Invocation.method(
        #getBool,
        [key],
      )) as bool?);

  @override
  int? getInt(String? key) => (super.noSuchMethod(Invocation.method(
        #getInt,
        [key],
      )) as int?);

  @override
  double? getDouble(String? key) => (super.noSuchMethod(Invocation.method(
        #getDouble,
        [key],
      )) as double?);

  @override
  String? getString(String? key) => (super.noSuchMethod(Invocation.method(
        #getString,
        [key],
      )) as String?);

  @override
  bool containsKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #getStringList,
        [key],
      )) as List<String>?);

  @override
  _i6.Future<bool> setBool(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> setInt(
    String? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInt,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> setDouble(
    String? key,
    double? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDouble,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> setString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> setStringList(
    String? key,
    List<String>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setStringList,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> commit() => (super.noSuchMethod(
        Invocation.method(
          #commit,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
