// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5Ox6r37DWCZCKxmbziEKO6llVDZ4g_j0',
    appId: '1:149697014585:web:0b01bf7eae8dca160716e8',
    messagingSenderId: '149697014585',
    projectId: 'venturelink-5b045',
    authDomain: 'venturelink-5b045.firebaseapp.com',
    storageBucket: 'venturelink-5b045.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5Ox6r37DWCZCKxmbziEKO6llVDZ4g_j0',
    appId: '1:149697014585:android:0b01bf7eae8dca160716e8',
    messagingSenderId: '149697014585',
    projectId: 'venturelink-5b045',
    storageBucket: 'venturelink-5b045.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5Ox6r37DWCZCKxmbziEKO6llVDZ4g_j0',
    appId: '1:149697014585:ios:0b01bf7eae8dca160716e8',
    messagingSenderId: '149697014585',
    projectId: 'venturelink-5b045',
    storageBucket: 'venturelink-5b045.firebasestorage.app',
    iosBundleId: 'com.xprience.venturelink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5Ox6r37DWCZCKxmbziEKO6llVDZ4g_j0',
    appId: '1:149697014585:ios:0b01bf7eae8dca160716e8',
    messagingSenderId: '149697014585',
    projectId: 'venturelink-5b045',
    storageBucket: 'venturelink-5b045.firebasestorage.app',
    iosBundleId: 'com.xprience.venturelink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5Ox6r37DWCZCKxmbziEKO6llVDZ4g_j0',
    appId: '1:149697014585:web:0b01bf7eae8dca160716e8',
    messagingSenderId: '149697014585',
    projectId: 'venturelink-5b045',
    authDomain: 'venturelink-5b045.firebaseapp.com',
    storageBucket: 'venturelink-5b045.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );
}
