// Mocks generated by Mockito 5.4.4 from annotations
// in venturelink/test/data/providers/subscription_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:venturelink/data/models/payment_method_model.dart' as _i7;
import 'package:venturelink/data/models/payment_session_model.dart' as _i3;
import 'package:venturelink/data/models/subscription_plan_model.dart' as _i2;
import 'package:venturelink/data/repositories/subscription_repository.dart'
    as _i5;
import 'package:venturelink/data/services/subscription_api_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSubscriptionPlanModel_0 extends _i1.SmartFake
    implements _i2.SubscriptionPlanModel {
  _FakeSubscriptionPlanModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaymentSessionModel_1 extends _i1.SmartFake
    implements _i3.PaymentSessionModel {
  _FakePaymentSessionModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSubscriptionModel_2 extends _i1.SmartFake
    implements _i2.SubscriptionModel {
  _FakeSubscriptionModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCancelSubscriptionResponse_3 extends _i1.SmartFake
    implements _i4.CancelSubscriptionResponse {
  _FakeCancelSubscriptionResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SubscriptionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionRepository extends _i1.Mock
    implements _i5.SubscriptionRepository {
  MockSubscriptionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i2.SubscriptionPlanModel>> getSubscriptionPlans(
          {bool? forceRefresh = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubscriptionPlans,
          [],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i6.Future<List<_i2.SubscriptionPlanModel>>.value(
            <_i2.SubscriptionPlanModel>[]),
      ) as _i6.Future<List<_i2.SubscriptionPlanModel>>);

  @override
  _i6.Future<_i2.SubscriptionPlanModel> getSubscriptionPlanDetails(
          String? planId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubscriptionPlanDetails,
          [planId],
        ),
        returnValue: _i6.Future<_i2.SubscriptionPlanModel>.value(
            _FakeSubscriptionPlanModel_0(
          this,
          Invocation.method(
            #getSubscriptionPlanDetails,
            [planId],
          ),
        )),
      ) as _i6.Future<_i2.SubscriptionPlanModel>);

  @override
  _i6.Future<List<_i7.PaymentMethodModel>> getPaymentMethods(
          {bool? forceRefresh = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaymentMethods,
          [],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i6.Future<List<_i7.PaymentMethodModel>>.value(
            <_i7.PaymentMethodModel>[]),
      ) as _i6.Future<List<_i7.PaymentMethodModel>>);

  @override
  _i6.Future<_i2.SubscriptionModel?> getCurrentSubscription(
          {bool? forceRefresh = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentSubscription,
          [],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i6.Future<_i2.SubscriptionModel?>.value(),
      ) as _i6.Future<_i2.SubscriptionModel?>);

  @override
  _i6.Future<_i3.PaymentSessionModel> createSubscriptionPayment({
    required String? planId,
    required String? currency,
    required String? paymentMethod,
    String? phoneNumber,
    String? successUrl,
    String? cancelUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSubscriptionPayment,
          [],
          {
            #planId: planId,
            #currency: currency,
            #paymentMethod: paymentMethod,
            #phoneNumber: phoneNumber,
            #successUrl: successUrl,
            #cancelUrl: cancelUrl,
          },
        ),
        returnValue: _i6.Future<_i3.PaymentSessionModel>.value(
            _FakePaymentSessionModel_1(
          this,
          Invocation.method(
            #createSubscriptionPayment,
            [],
            {
              #planId: planId,
              #currency: currency,
              #paymentMethod: paymentMethod,
              #phoneNumber: phoneNumber,
              #successUrl: successUrl,
              #cancelUrl: cancelUrl,
            },
          ),
        )),
      ) as _i6.Future<_i3.PaymentSessionModel>);

  @override
  _i6.Future<_i3.PaymentSessionModel> checkPaymentStatus(String? paymentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkPaymentStatus,
          [paymentId],
        ),
        returnValue: _i6.Future<_i3.PaymentSessionModel>.value(
            _FakePaymentSessionModel_1(
          this,
          Invocation.method(
            #checkPaymentStatus,
            [paymentId],
          ),
        )),
      ) as _i6.Future<_i3.PaymentSessionModel>);

  @override
  _i6.Future<_i2.SubscriptionModel> createSubscription({
    required String? planId,
    required String? currency,
    bool? autoRenew = true,
    String? paymentMethodId,
    String? paymentSessionId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSubscription,
          [],
          {
            #planId: planId,
            #currency: currency,
            #autoRenew: autoRenew,
            #paymentMethodId: paymentMethodId,
            #paymentSessionId: paymentSessionId,
          },
        ),
        returnValue:
            _i6.Future<_i2.SubscriptionModel>.value(_FakeSubscriptionModel_2(
          this,
          Invocation.method(
            #createSubscription,
            [],
            {
              #planId: planId,
              #currency: currency,
              #autoRenew: autoRenew,
              #paymentMethodId: paymentMethodId,
              #paymentSessionId: paymentSessionId,
            },
          ),
        )),
      ) as _i6.Future<_i2.SubscriptionModel>);

  @override
  _i6.Future<_i4.CancelSubscriptionResponse> cancelSubscription({
    required String? subscriptionId,
    String? reason,
    bool? cancelImmediately = false,
    String? feedback,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelSubscription,
          [],
          {
            #subscriptionId: subscriptionId,
            #reason: reason,
            #cancelImmediately: cancelImmediately,
            #feedback: feedback,
          },
        ),
        returnValue: _i6.Future<_i4.CancelSubscriptionResponse>.value(
            _FakeCancelSubscriptionResponse_3(
          this,
          Invocation.method(
            #cancelSubscription,
            [],
            {
              #subscriptionId: subscriptionId,
              #reason: reason,
              #cancelImmediately: cancelImmediately,
              #feedback: feedback,
            },
          ),
        )),
      ) as _i6.Future<_i4.CancelSubscriptionResponse>);

  @override
  _i6.Future<_i2.SubscriptionModel> reactivateSubscription(
          String? subscriptionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #reactivateSubscription,
          [subscriptionId],
        ),
        returnValue:
            _i6.Future<_i2.SubscriptionModel>.value(_FakeSubscriptionModel_2(
          this,
          Invocation.method(
            #reactivateSubscription,
            [subscriptionId],
          ),
        )),
      ) as _i6.Future<_i2.SubscriptionModel>);

  @override
  _i6.Future<_i2.SubscriptionModel> changePlan({
    required String? subscriptionId,
    required String? newPlanId,
    bool? prorate = true,
    String? currency,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePlan,
          [],
          {
            #subscriptionId: subscriptionId,
            #newPlanId: newPlanId,
            #prorate: prorate,
            #currency: currency,
          },
        ),
        returnValue:
            _i6.Future<_i2.SubscriptionModel>.value(_FakeSubscriptionModel_2(
          this,
          Invocation.method(
            #changePlan,
            [],
            {
              #subscriptionId: subscriptionId,
              #newPlanId: newPlanId,
              #prorate: prorate,
              #currency: currency,
            },
          ),
        )),
      ) as _i6.Future<_i2.SubscriptionModel>);
}
